### ISSUE TITLE
コメント機能が追加されるとshowのスタイルが微妙に崩れる

### ISSUE THREAD

**Issue by JunichiIto** [JunichiIto/fjord-books_app-2023#26]
コメント欄から下の部分が意図したデザインになってなさそう。

## 06-comments （コメント機能追加前）

<img width="723" alt="Screenshot 2023-01-24 at 11 17 34" src="https://user-images.githubusercontent.com/1148320/214199444-9f9b3f1d-8f47-4c70-a806-93b51f89fd05.png">

## 07-report_mention（コメント機能追加後）

<img width="718" alt="Screenshot 2023-01-24 at 11 19 27" src="https://user-images.githubusercontent.com/1148320/214199574-6df3bb76-938b-4f63-b412-1baa12dfc807.png">

**Comment by JunichiIto** [comment]
@machida これ、確認＆修正をお願いしたいです。

- コメント機能を追加する前のブランチ = https://github.com/JunichiIto/fjord-books_app-2023/tree/06-comments
- コメント機能を追加した後のブランチ = https://github.com/JunichiIto/fjord-books_app-2023/tree/07-report_mention

CSSを確認したところ、今回もDOMの構造に依存しているところで問題が起きてそうな印象です。

あと、コメントの削除ボタンをインライン表示するために以下のCSSを追加していますが、これは必要に応じて削除してもらっても大丈夫です。

https://github.com/JunichiIto/fjord-books_app-2023/blob/07-report_mention/app/assets/stylesheets/comments.css

「DOMの構造に依存」は不安定なので、view側に何か細工を入れる、というアプローチでも良いかなーと思ったりしています。

お手すきの際にご確認よろしくお願いします 🙏

**Comment by machida** [comment]
@JunichiIto 

確認ありがとうございます🙏

> 「DOMの構造に依存」は不安定なので、view側に何か細工を入れる、というアプローチでも良いかなーと思ったりしています。

確かにそうですね。逆に手を入れないで無理やりデザインを適用するのは混乱を招きそうです。
こちら、view側に何か細工を入れるアプローチで修正をしていきますー

**Comment by JunichiIto** [comment]
@machida お忙しいところすいません。これ、対応はまだしばらくかかりそうですか？

**Comment by machida** [comment]
@JunichiIto すいません、ちょうど今 PR を送っていたところでした🙇‍♂️

https://github.com/JunichiIto/fjord-books_app-2023/pull/30
こちらになります。

erb に必要な変更を確認するために、`07-report_mention` に向けて PR を送りましたが、ここにこのように送って欲しいなどありましたら言っていただけると助かります🙏
